### ISSUE TITLE
why!!

### ISSUE THREAD

**Issue by ElLuxurys** [Android1337/Fortnite-cheat-source-internal-self-leak#1]
why did you leak a zgui cheat 😞😞😞😞

**Comment by taubensuppe** [comment]
ye kinda sad the com is getting broken and all devs get doxxed and people r leaking srces and epic will fix everything and soon theres nothing what u can do anymore

**Comment by Android1337** [comment]
a guy scammed me for that source and he is selling it now, so why not releasing it :)
